log_errors=On
error_log=/home/shoppingbulg/public_html/espravki.com/php_errors.log
date.timezone="europe/sofia"
expose_php=on
display_errors=on
short_open_tag=on
allow_url_fopen=on
register_globals=off
; magic_quotes_gpc=on
output_buffering=off
upload_max_filesize=100M
post_max_size=100M
max_input_time=30
session.gs_maxlifetime=1
memory_limit=100M
max_execution_time=2
